services:
  backend:
    build:
      context: ./backend_tapiceria_api
      dockerfile: dockerfile
    container_name: tapiceria_backend
    ports:
      - '10000:10000'
    env_file:
      - .env
    environment:
      - USE_REMOTE_DB=True
      - PORT=10000
      - DEBUG=True
    volumes:
      - ./backend_tapiceria_api:/app
    networks:
      - tapiceria_network
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: tapiceria_frontend
    ports:
      - '5173:5173'
    env_file:
      - .env
    # La URL se inyectar√° desde el .env que editaremos manualmente una sola vez
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - tapiceria_network
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tapiceria_tunnel
    restart: always
    command: tunnel --url http://tapiceria_backend:10000
    networks:
      - tapiceria_network # Crucial para conectar con el backend
    depends_on:
      - backend

networks:
  tapiceria_network:
    driver: bridge
